openapi: 3.0.0
info:
  title: Temples API
  version: 1.0.0
  description: API for accessing and managing temple data

servers:
  - url: http://localhost:8080

paths:
  /temples:
    get:
      summary: Get all temples
      tags:
        - Temples
      responses:
        '200':
          description: List of temples

    post:
      summary: Create a new temple
      tags:
        - Temples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                templeName:
                  type: string
                location:
                  type: string
                dedicated:
                  type: string
      responses:
        '201':
          description: Temple created

  /temples/{temple_id}:
    get:
      summary: Get temple by ID
      tags:
        - Temples
      parameters:
        - name: temple_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Temple found
        '404':
          description: Temple not found

    put:
      summary: Update a temple
      tags:
        - Temples
      parameters:
        - name: temple_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                templeName:
                  type: string
                location:
                  type: string
                dedicated:
                  type: string
      responses:
        '200':
          description: Temple updated

    delete:
      summary: Delete a temple
      tags:
        - Temples
      parameters:
        - name: temple_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Temple deleted
        '404':
          description: Temple not found
